/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.inatel.Av3.view;

import br.inatel.Av3.Controller.Arquivo;
import br.inatel.Av3.Exceptions.CamposVaziosException;
import br.inatel.Av3.Exceptions.CpfInvalidoException;
import br.inatel.Av3.Exceptions.NumeroErradoException;
import br.inatel.Av3.model.Candidato;
import br.inatel.Av3.model.Voto;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author burns
 */
public class Tela1 extends javax.swing.JFrame {

    /**
     * Creates new form Tela1
     */
    int indice = 0;
    Arquivo a1 = new Arquivo("1");
    Arquivo a2 = new Arquivo("2");
    Arquivo a3 = new Arquivo("3");
    //criando as listas dos votos que serao passadas para o arquivo
    ArrayList<Voto> listaVotos1 = new ArrayList();
    ArrayList<Voto> listaVotos2 = new ArrayList();
    ArrayList<Voto> listaVotos3 = new ArrayList();
    //criando os candidatos
    Candidato c1 = new Candidato();
    Candidato c2 = new Candidato();
    Candidato c3 = new Candidato();

    public Tela1() {
        initComponents();
        listaVotos1 = a1.ler("1");
        listaVotos2 = a2.ler("2");
        listaVotos3 = a3.ler("3");
        this.setLocationRelativeTo(null);
        //inicializando candidatos
        c1.setNome("Paulinho anão");
        c1.setChamada("Dos males o menor!");
        c1.setNum(77);
        
        c2.setNome("Rogerão");
        c2.setChamada("O amigo do povão!");
        c2.setNum(51);
        
        c3.setNome("Darth Verde");
        c3.setChamada("O mais honesto das galaxias!");
        c3.setNum(43);
      
        //setando btns e lbls invisiveis
        
        lbl_cont1.setText("77");
        lbl_cont2.setText("51");
        lbl_cont3.setText("43");
        lbl_Static_votos.setVisible(false);
        lbl_Static_votos1.setVisible(false);
        lbl_Static_votos2.setVisible(false);
        btn_okay.setVisible(false);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lbl_cpf = new javax.swing.JLabel();
        txt_cpf = new javax.swing.JTextField();
        lbl_numero = new javax.swing.JLabel();
        txt_numero = new javax.swing.JTextField();
        btn_votar = new javax.swing.JButton();
        btn_finalizar = new javax.swing.JButton();
        btn_okay = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lbl_cand1 = new javax.swing.JLabel();
        lbl_cand2 = new javax.swing.JLabel();
        lbl_cand3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txta_anuncio = new javax.swing.JTextArea();
        lbl_cont1 = new javax.swing.JLabel();
        lbl_cont2 = new javax.swing.JLabel();
        lbl_cont3 = new javax.swing.JLabel();
        lbl_Static_votos = new javax.swing.JLabel();
        lbl_Static_votos1 = new javax.swing.JLabel();
        lbl_Static_votos2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Urna Eletrônica", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 12))); // NOI18N

        lbl_cpf.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lbl_cpf.setText("CPF");

        lbl_numero.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lbl_numero.setText("NÚMERO");

        btn_votar.setText("Votar");
        btn_votar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_votarActionPerformed(evt);
            }
        });

        btn_finalizar.setText("Finalizar");
        btn_finalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_finalizarActionPerformed(evt);
            }
        });

        btn_okay.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btn_okay.setText("OK");
        btn_okay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_okayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_okay))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lbl_cpf)
                                .addComponent(txt_cpf)
                                .addComponent(lbl_numero)
                                .addComponent(txt_numero, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(btn_votar)
                                .addGap(18, 18, 18)
                                .addComponent(btn_finalizar)))
                        .addGap(0, 1, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_cpf)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_numero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_votar)
                    .addComponent(btn_finalizar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_okay)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Resultados :", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 12))); // NOI18N

        lbl_cand1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lbl_cand1.setText("Paulinho Anão");

        lbl_cand2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lbl_cand2.setText("Rogerão");

        lbl_cand3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lbl_cand3.setText("Darth Verde");

        txta_anuncio.setColumns(20);
        txta_anuncio.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txta_anuncio.setRows(5);
        txta_anuncio.setToolTipText("");
        jScrollPane1.setViewportView(txta_anuncio);

        lbl_cont1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lbl_cont1.setText("0");

        lbl_cont2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lbl_cont2.setText("0");

        lbl_cont3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lbl_cont3.setText("0");

        lbl_Static_votos.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lbl_Static_votos.setText("Votos");

        lbl_Static_votos1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lbl_Static_votos1.setText("Votos");

        lbl_Static_votos2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lbl_Static_votos2.setText("Votos");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_cand1)
                    .addComponent(lbl_cand3)
                    .addComponent(lbl_cand2))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lbl_cont2)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_Static_votos1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lbl_cont3)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_Static_votos2))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lbl_cont1)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_Static_votos)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_cand1)
                    .addComponent(lbl_cont1)
                    .addComponent(lbl_Static_votos))
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_cont2)
                    .addComponent(lbl_cand2)
                    .addComponent(lbl_Static_votos1))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_cand3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_cont3)
                    .addComponent(lbl_Static_votos2))
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 438, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_votarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_votarActionPerformed
        votar();
        limparCampos();
    }//GEN-LAST:event_btn_votarActionPerformed

    private void btn_finalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_finalizarActionPerformed
        fazVotacao();
    }//GEN-LAST:event_btn_finalizarActionPerformed

    private void btn_okayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_okayActionPerformed
        limparCampos();
        
    }//GEN-LAST:event_btn_okayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_finalizar;
    private javax.swing.JButton btn_okay;
    private javax.swing.JButton btn_votar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_Static_votos;
    private javax.swing.JLabel lbl_Static_votos1;
    private javax.swing.JLabel lbl_Static_votos2;
    private javax.swing.JLabel lbl_cand1;
    private javax.swing.JLabel lbl_cand2;
    private javax.swing.JLabel lbl_cand3;
    private javax.swing.JLabel lbl_cont1;
    private javax.swing.JLabel lbl_cont2;
    private javax.swing.JLabel lbl_cont3;
    private javax.swing.JLabel lbl_cpf;
    private javax.swing.JLabel lbl_numero;
    private javax.swing.JTextField txt_cpf;
    private javax.swing.JTextField txt_numero;
    private javax.swing.JTextArea txta_anuncio;
    // End of variables declaration//GEN-END:variables

    private void votar() {
        Voto v = new Voto();
        try {
            v.setCpf(txt_cpf.getText());
            v.setNum(txt_numero.getText());
            if (txt_numero.getText().equals("77")) {
                listaVotos1.add(v);
                a1.salvarArquivo(listaVotos1, "1");
            } else if (txt_numero.getText().equals("51")) {
                listaVotos2.add(v);
                a2.salvarArquivo(listaVotos2, "2");
            } else if (txt_numero.getText().equals("43")) {
                listaVotos3.add(v);
                a3.salvarArquivo(listaVotos3, "3");
            }

            JOptionPane.showMessageDialog(null, "voto realizado com sucesso!");
        } catch (CamposVaziosException e) {
            System.out.println(e.getMessage());
        } catch (CpfInvalidoException e1) {
            System.out.println(e1.getMessage());
        } catch (NumeroErradoException e2) {
            System.out.println(e2.getMessage());
        } finally {
            limparCampos();
            btn_okay.setVisible(false);
        }

    }

    private void limparCampos() {
        txt_cpf.setText("");
        txt_numero.setText("");
        txta_anuncio.setText("");
        lbl_cont1.setText("77");
        lbl_cont2.setText("51");
        lbl_cont3.setText("43");
        lbl_Static_votos.setVisible(false);
        lbl_Static_votos1.setVisible(false);
        lbl_Static_votos2.setVisible(false);
    }

    private void fazVotacao() {
        //listas aux para contar os votos pelo arquivo
        ArrayList<String> cpfs1 = new ArrayList();
        ArrayList<String> cpfs2 = new ArrayList();
        ArrayList<String> cpfs3 = new ArrayList();
        //percorre os 3 arquivos e preenche as listas
        for (Voto i : a1.ler("1")) {
            cpfs1.add(i.getCpf());
        }
        for (Voto i : a2.ler("2")) {
            cpfs2.add(i.getCpf());
        }
        for (Voto i : a3.ler("3")) {
            cpfs3.add(i.getCpf());
        }
        //mostra as lbl de voto
        lbl_Static_votos.setVisible(true);
        lbl_Static_votos1.setVisible(true);
        lbl_Static_votos2.setVisible(true);
        //mostra quantos votos cada um recebeu 
        lbl_cont1.setText(cpfs1.size() + "");
        lbl_cont2.setText(cpfs2.size() + "");
        lbl_cont3.setText(cpfs3.size() + "");
        //variavel aux para fazer a comparação 
        int aux1, aux2, aux3;
        aux1 = cpfs1.size();
        aux2 = cpfs2.size();
        aux3 = cpfs3.size();
        //menu de comparações

        if (aux1 > aux2 && aux1 > aux3) {
            txta_anuncio.setText("Com " + aux1 + " votos \n"
                    + "     O vencedor é : Paulinho Anão !");

        
        } else if (aux2 > aux1 && aux2 > aux3) {
            txta_anuncio.setText("Com " + aux2 + " votos \n"
                    + "     O vencedor é : Rogerão !");

           

        } else if (aux3 > aux2 && aux3 > aux1) {
            txta_anuncio.setText("Com " + aux3 + " votos \n"
                    + "     O vencedor é : Darth Verde !");

           
        } else if (aux1 == aux2 && aux1 > aux3) {
            fazerSegundoTurno(c1, c2);
        } else if (aux1 == aux3 && aux1 > aux2) {
            fazerSegundoTurno(c2, c3);
        } else if (aux3 == aux2 && aux2 > aux1) {
            fazerSegundoTurno(c2, c1);
        }
        
    }

    private void fazerSegundoTurno(Candidato a, Candidato b) {
        btn_okay.setVisible(true);
        JOptionPane.showMessageDialog(null, "Precisamos de um voto de desempate!");
        txta_anuncio.setText("     Essa não ocorreu um empate! \n"
                + "       " + a.getNome() + " VS " + b.getNome());

    }

   
      
    }

   

